
services:
  app:
    build: .
    container_name: my_go_app
    restart: always
    ports:
      - "8070:8070"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    container_name: my_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: multilang1
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: my_redis
    restart: always
    ports:
      - "6379:6379"

  pgadmin:
    image: adminer
    restart: always
    ports:
      - "9012:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=my_postgres


volumes:
  postgres_data: