services:
  shop_app:
    build: .
    restart: always
    ports:
      - "8070:8070"
    env_file:
      - .env
    depends_on:
      - shop_postgres
      - shop_redis

  shop_postgres:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: multilang1
    volumes:
      - postgres_data:/var/lib/postgresql/data

  shop_redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  shop_pgadmin:
    image: adminer
    restart: always
    ports:
      - "9012:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=my_postgres


volumes:
  postgres_data:
